SELECT REPLACE(ERP.FIRST_NM, ',' , '') AS FIRST_NAME, 
REPLACE(ERP.LAST_NM, ', ' , ' ') AS LAST_NAME, 
ERP.EMAIL_ADDR_TEXT AS EMAIL_ADDR,
ERO.OPTIN_FLAG AS OPTIN_FLAG, 
EP.HOME AS HOME_NBR,
EP.MOBILE AS CELL_NBR,
REPLACE(AD.ADDR_1_TEXT, ', ' , ' ') AS ADDRESS_1,
REPLACE(AD.ADDR_2_TEXT, ', ' ,' ') AS ADDRESS_2, 
REPLACE(AD.CITY_NM, ', ' , '') AS CITY_NAME, 
NVL(REPLACE(AD.STATE_PROV_CD, ', ' , ''), ' ') AS STATE_PROV_CD,
CASE
    WHEN (LOWER(AD.COUNTRY_CD) = 'US') THEN '1'
    WHEN (LOWER(AD.COUNTRY_CD) = 'CA') THEN '2'
    WHEN (LOWER(AD.COUNTRY_CD) = 'MX') THEN '3'
    ELSE '0'
END AS COUNTRY_CODE,
NVL(REPLACE(AD.POSTAL_CD, ', ' , ''), ' ') AS POSTAL_CODE,
'' AS ACCOUNT_NAME, 
PI.DEALER AS DEALER_CODE,
'' AS DRL_MAILING_STREET, 
'' AS DRL_MAILING_CITY, 
'' AS DRL_MAILING_STATE_PROVICE,
'' AS DRL_MAILING_ZIP, 
'' AS DRL_PHONE, 
'' AS DRL_EMAIL, 
ERV.VIN_ID,
TO_CHAR(ERS.STATUS_TIMSTM, 'DD-MON-YY HH24:MI:SS' ),
CASE
    WHEN (LOWER(AD.COUNTRY_CD) = '1') THEN 'en_CA'
    WHEN (LOWER(AD.COUNTRY_CD) = '2') THEN 'fr_CA'
    ELSE 'en_US'
END AS LANG_CODE,
REPLACE(AD.ADDR_1_TEXT, ', ' , ' ') AS MAIL_ADDRESS_1,
REPLACE(AD.ADDR_2_TEXT, ', ' ,' ') AS MAIL_ADDRESS_2, 
REPLACE(AD.CITY_NM, ', ' , '') AS MAIL_CITY_NAME, 
NVL(REPLACE(AD.STATE_PROV_CD, ', ' , ''), ' ') AS MAIL_STATE_PROV_CD,
CASE
    WHEN (LOWER(AD.COUNTRY_CD) = 'US') THEN '1'
    WHEN (LOWER(AD.COUNTRY_CD) = 'CA') THEN '2'
    WHEN (LOWER(AD.COUNTRY_CD) = 'MX') THEN '3'
    ELSE '0'
END AS MAIL_COUNTRY_CODE,
NVL(REPLACE(AD.POSTAL_CD, ', ' , ''), ' ') AS MAIL_POSTAL_CODE,
NVL(ERP.ORGANIZATION_NM,'') AS DEALER_NAME,
REPLACE(AD.ADDR_1_TEXT, ', ' , ' ') AS DRL_ADDRESS_1,
REPLACE(AD.ADDR_2_TEXT, ', ' ,' ') AS DRL_ADDRESS_2, 
REPLACE(AD.CITY_NM, ', ' , '') AS DRL_CITY_NAME, 
NVL(REPLACE(AD.STATE_PROV_CD, ', ' , ''), ' ') AS DRL_STATE_PROV_CD,
CASE
    WHEN (LOWER(AD.COUNTRY_CD) = 'US') THEN '1'
    WHEN (LOWER(AD.COUNTRY_CD) = 'CA') THEN '2'
    WHEN (LOWER(AD.COUNTRY_CD) = 'MX') THEN '3'
    ELSE '0'
END AS DRL_COUNTRY_CODE,
NVL(REPLACE(AD.POSTAL_CD, ', ' , ''), ' ') AS DRL_POSTAL_CODE,
NVL(ERPP.PHONE_NBR,'') AS PHONE_NUMBER
FROM ENROLL_REQ ER
JOIN ENROLL_REQ_PARTY ERP
    ON ERP.ENROLL_REQ_ID =  ER.ENROLL_REQ_ID
LEFT JOIN ADDRESS AD 
    ON AD.ADDRESS_ID = ERP.ADDRESS_ID
LEFT JOIN ENROLL_REQ_VEH ERV
    ON ERV.ENROLL_REQ_ID = ER.ENROLL_REQ_ID
LEFT JOIN ENROLL_REQ_STATUS ERS
    ON ER.ENROLL_REQ_ID = ERS.ENROLL_REQ_ID
LEFT JOIN ENROLL_REQ_OPTIN ERO
    ON ERO.ENROLL_REQ_ID = ER.ENROLL_REQ_ID
LEFT JOIN ENROLL_REQ_PARTY_PHONE ERPP 
    ON ERPP.ENROLL_REQ_PARTY_ID =  ERP.ENROLL_REQ_PARTY_ID
JOIN (SELECT DISTINCT (EL.ENROLL_REQ_PARTY_ID), E2.PHONE_NBR AS HOME, E3.PHONE_NBR AS MOBILE 
    FROM ENROLL_REQ_PARTY_PHONE EL 
        LEFT JOIN ENROLL_REQ_PARTY_PHONE E2 ON EL.ENROLL_REQ_PARTY_ID = E2.ENROLL_REQ_PARTY_ID AND E2.PHONE_TYPE_CD = 'HOME'
        LEFT JOIN ENROLL_REQ_PARTY_PHONE E3 ON EL.ENROLL_REQ_PARTY_ID = E3.ENROLL_REQ_PARTY_ID AND E3.PHONE_TYPE_CD = 'MOBILE') EP ON EP.ENROLL_REQ_PARTY_ID = ERP.ENROLL_REQ_PARTY_ID
JOIN (SELECT DISTINCT(P1.ENROLL_REQ_PARTY_ID), P2.PARTY_IDENT_VAL AS DEALER
      FROM ENROLL_REQ_PARTY_IDENT P2
      LEFT JOIN ENROLL_REQ_PARTY_IDENT P1 ON P1.ENROLL_REQ_PARTY_ID = P2.ENROLL_REQ_PARTY_ID AND P2.PARTY_IDENT_TYPE_CD = 'DEALER_CODE') PI
ON PI.ENROLL_REQ_PARTY_ID = ERP.ENROLL_REQ_PARTY_ID
WHERE erp.enroll_role_cd =  'SUBSCRIBER'
AND TRUNC (er.created_timstm) >= (TRUNC (SYSDATE)-$DAYVAR$); 